# Changelog for `2162d953c8d0c13b775dcf3ad4e0b10e7a6e97d1`
> Generated by GPT-4.1 from 4 commits between `2162d953c8d0c13b775dcf3ad4e0b10e7a6e97d1` and `0995a07c886b38e794c407f9ad152d65a32c8971`


Use the 👍 and 👎 buttons in the editor toolbar to provide feedback on this AI response. *Your feedback helps us improve our AI features.*

----

### Added
- Adds scripts for loading and analyzing real Blue Social Competences data
- Adds a CONTRIBUTING.md guide to help users get started

### Changed
- Changes project planning with the addition of an initial plan

### Fixed
- Fixes setup blockers for smoother project installation
