# Changelog for `c068036473875707f9d80542474b982f538c8f67`
> Generated by GPT-4.1 from 3 commits between `c068036473875707f9d80542474b982f538c8f67` and `0995a07c886b38e794c407f9ad152d65a32c8971`


Use the 👍 and 👎 buttons in the editor toolbar to provide feedback on this AI response. *Your feedback helps us improve our AI features.*

----

### Added
- Adds scripts for loading and analyzing real Blue Social Competences data
- Adds a CONTRIBUTING.md guide to help users get started

### Changed
- Changes project planning with the addition of an initial plan

### Fixed
- Fixes setup blockers for smoother project installation
