# morskamary research API credentials
# Generated by scripts/bootstrap_research_secrets.ps1
# DO NOT COMMIT THIS FILE. It is gitignored.
# Dot-source to load: . .\.env.ps1

$env:CROSSREF_MAILTO = 'robert.bartlomiejski@usz.edu.pl'
$env:ELSEVIER_API_KEY = '4d3de67706dc9afec5975361fe0d374f'
$env:SCOPUS_API_KEY = '027ce3ae05377c9546a2f9e1b21f70be'
$env:WOS_API_KEY = '7f59af901d2d86f78a1fd60c1bf9426a'
$env:SCIVAL_API_KEY = '7f59af901d2d86f78a1fd60c1bf9426a'
