<#
.SYNOPSIS
    One-time secure setup for morskamary research API credentials.

.DESCRIPTION
    Reads API credentials interactively and stores them in the selected backend.

    Supported backends:
      DotEnv   - write .env and .env.ps1 in repo root
      Gcp      - upload secret versions to Google Secret Manager
      Github   - print gh CLI commands for GitHub repository secrets
      UserEnv  - alias for DotEnv
      user-env - alias for DotEnv

    Secret values are never printed. The .env and .env.ps1 files are gitignored.

.PARAMETER Backend
    DotEnv, Gcp, Github, UserEnv, or user-env.

.PARAMETER ProjectId
    Google Cloud project ID. Required when Backend is Gcp.

.EXAMPLE
    .\scripts\bootstrap_research_secrets.ps1 -Backend DotEnv
    . .\.env.ps1

.EXAMPLE
    .\scripts\bootstrap_research_secrets.ps1 -Backend Gcp -ProjectId intricate-shard-477117-f7

.EXAMPLE
    .\scripts\bootstrap_research_secrets.ps1 -Backend Github
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet('DotEnv', 'Gcp', 'Github', 'UserEnv', 'user-env', IgnoreCase = $true)]
    [string]$Backend,

    [Parameter(Mandatory = $false)]
    [string]$ProjectId = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$BackendNorm = $Backend.ToLowerInvariant()
if ($BackendNorm -eq "userenv" -or $BackendNorm -eq "user-env") {
    $BackendNorm = "dotenv"
}

if ($BackendNorm -eq "gcp" -and [string]::IsNullOrWhiteSpace($ProjectId)) {
    Write-Error "ERROR: -ProjectId is required when -Backend is Gcp."
    exit 1
}

$RepoRoot = Split-Path -Parent $PSScriptRoot
$DotEnvSh = Join-Path $RepoRoot ".env"
$DotEnvPs1 = Join-Path $RepoRoot ".env.ps1"

$SecretMap = [ordered]@{
    CROSSREF_MAILTO  = @{ GcpName = "crossref-mailto";  Label = "Crossref polite contact email" }
    ELSEVIER_API_KEY = @{ GcpName = "elsevier-api-key"; Label = "Elsevier platform API key" }
    SCOPUS_API_KEY   = @{ GcpName = "scopus-api-key";   Label = "Scopus API key" }
    WOS_API_KEY      = @{ GcpName = "wos-api-key";      Label = "Web of Science API key" }
    SCIVAL_API_KEY   = @{ GcpName = "scival-api-key";   Label = "SciVal API key" }
}

function Convert-SecureStringToPlainText {
    param(
        [Parameter(Mandatory = $true)]
        [Security.SecureString]$SecureValue
    )

    $ptr = [IntPtr]::Zero
    try {
        $ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecureValue)
        return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)
    } finally {
        if ($ptr -ne [IntPtr]::Zero) {
            [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
        }
    }
}

function ConvertTo-PowerShellSingleQuoted {
    param([string]$Value)
    return $Value.Replace("'", "''")
}

function ConvertTo-BashDoubleQuoted {
    param([string]$Value)
    $escaped = $Value.Replace("\", "\\")
    $escaped = $escaped.Replace('"', '\"')
    $escaped = $escaped.Replace('$', '\$')
    $escaped = $escaped.Replace('`', '\`')
    return $escaped
}

function Write-Utf8TextFile {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,

        [Parameter(Mandatory = $true)]
        [AllowEmptyString()]
        [string[]]$Lines,

        [Parameter(Mandatory = $false)]
        [bool]$EmitBom = $false
    )

    $newline = [Environment]::NewLine
    $content = [string]::Join($newline, $Lines) + $newline
    $encoding = New-Object System.Text.UTF8Encoding($EmitBom)
    [System.IO.File]::WriteAllText($Path, $content, $encoding)
}

if ($BackendNorm -eq "github") {
    Write-Host ""
    Write-Host "GitHub Actions secrets. Run these commands with GitHub CLI:"
    Write-Host ""
    foreach ($varName in $SecretMap.Keys) {
        Write-Host "  gh secret set $varName"
    }
    Write-Host ""
    Write-Host "Verify:"
    Write-Host "  gh secret list"
    Write-Host ""
    exit 0
}

Write-Host ""
Write-Host "=== morskamary Research API Bootstrap (PowerShell) ===" -ForegroundColor Cyan
Write-Host "Backend: $BackendNorm"
Write-Host ""
Write-Host "Press ENTER to skip any credential you do not have yet."
Write-Host "Values are read securely and never displayed."
Write-Host ""

$Values = @{}
foreach ($varName in $SecretMap.Keys) {
    $label = $SecretMap[$varName].Label
    $secure = Read-Host -Prompt "Enter $label [ENTER to skip]" -AsSecureString
    $plain = Convert-SecureStringToPlainText -SecureValue $secure
    $Values[$varName] = $plain
}

Write-Host ""

switch ($BackendNorm) {
    "dotenv" {
        Write-Host "Writing local credential files:"
        Write-Host "  $DotEnvSh"
        Write-Host "  $DotEnvPs1"
        Write-Host ""

        $bashLines = @(
            "# morskamary research API credentials",
            "# Generated by scripts/bootstrap_research_secrets.ps1",
            "# DO NOT COMMIT THIS FILE. It is gitignored.",
            ""
        )

        $ps1Lines = @(
            "# morskamary research API credentials",
            "# Generated by scripts/bootstrap_research_secrets.ps1",
            "# DO NOT COMMIT THIS FILE. It is gitignored.",
            "# Dot-source to load: . .\.env.ps1",
            ""
        )

        foreach ($varName in $SecretMap.Keys) {
            $val = $Values[$varName]
            if (-not [string]::IsNullOrEmpty($val)) {
                $bashVal = Escape-BashDoubleQuoted -Value $val
                $psVal = Escape-PowerShellSingleQuoted -Value $val

                $bashLines += "export $varName=""$bashVal"""
                $ps1Lines += "`$env:$varName = '$psVal'"

                Write-Host "  $varName = <set>"
            } else {
                $bashLines += "# export $varName=  # skipped"
                $ps1Lines += "# `$env:$varName = ''  # skipped"
                Write-Host "  $varName = skipped"
            }
        }

        Write-Utf8TextFile -Path $DotEnvSh -Lines $bashLines -EmitBom $false
        Write-Utf8TextFile -Path $DotEnvPs1 -Lines $ps1Lines -EmitBom $true

        Write-Host ""
        Write-Host "Done."
        Write-Host "Load into the current PowerShell session with:"
        Write-Host "  . .\.env.ps1"
    }

    "gcp" {
        Write-Host "Uploading to Google Secret Manager project: $ProjectId"
        Write-Host ""

        foreach ($varName in $SecretMap.Keys) {
            $val = $Values[$varName]
            $secretName = $SecretMap[$varName].GcpName

            if ([string]::IsNullOrEmpty($val)) {
                Write-Host "  skip $secretName"
                continue
            }

            $tmpFile = [System.IO.Path]::GetTempFileName()
            try {
                [System.IO.File]::WriteAllText($tmpFile, $val, [System.Text.Encoding]::UTF8)

                $result = gcloud secrets versions add $secretName --project=$ProjectId --data-file=$tmpFile 2>&1
                if ($LASTEXITCODE -ne 0) {
                    Write-Error "ERROR: Failed to add version for $secretName`n$result"
                    exit 1
                }

                Write-Host "  OK $secretName"
            } finally {
                if (Test-Path $tmpFile) {
                    $length = ([System.IO.FileInfo]$tmpFile).Length
                    if ($length -gt 0) {
                        $zeroBytes = New-Object byte[] $length
                        [System.IO.File]::WriteAllBytes($tmpFile, $zeroBytes)
                    }
                    Remove-Item $tmpFile -Force
                }
            }
        }

        Write-Host ""
        Write-Host "Done. Verify with:"
        Write-Host "  gcloud secrets list --project=$ProjectId"
    }

    default {
        Write-Error "Unsupported backend: $Backend"
        exit 1
    }
}

foreach ($varName in @($Values.Keys)) {
    $Values[$varName] = $null
}

Write-Host ""
Write-Host "Next verification command:"
Write-Host "  python scripts/check_research_env.py"
