#!/usr/bin/env python3
"""
Validate research source output files for schema and provenance completeness.

Checks outputs generated by export_research_source_capabilities.py and the
smoke tests for expected keys and non-empty content.

Usage:
    python scripts/validate_research_source_outputs.py

Exit codes:
    0  All present output files are valid.
    1  One or more validation errors found.
"""

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

OUTPUTS_DIR = os.path.join(os.path.dirname(__file__), "..", "outputs")

ERRORS: list = []
WARNINGS: list = []


def _err(msg: str) -> None:
    ERRORS.append(msg)
    print(f"  ERROR: {msg}")


def _warn(msg: str) -> None:
    WARNINGS.append(msg)
    print(f"  WARN:  {msg}")


def validate_capabilities_json() -> None:
    """Validate outputs/research_source_capabilities.json if present."""
    path = os.path.join(OUTPUTS_DIR, "research_source_capabilities.json")
    if not os.path.isfile(path):
        _warn("research_source_capabilities.json not found (run export script first)")
        return

    with open(path, encoding="utf-8") as f:
        try:
            data = json.load(f)
        except json.JSONDecodeError as exc:
            _err(f"research_source_capabilities.json is not valid JSON: {exc}")
            return

    for key in ("generated_at", "providers"):
        if key not in data:
            _err(f"research_source_capabilities.json missing key: {key}")

    providers = data.get("providers", {})
    if "crossref" not in providers:
        _err("crossref provider missing from capabilities export")
    elif not providers["crossref"].get("configured"):
        _err("crossref should always be configured=true")

    print(f"  OK: research_source_capabilities.json ({len(providers)} providers)")


def validate_smoke_report() -> None:
    """Validate outputs/research_api_smoke_report.json if present."""
    path = os.path.join(OUTPUTS_DIR, "research_api_smoke_report.json")
    if not os.path.isfile(path):
        _warn("research_api_smoke_report.json not found (run smoke script first)")
        return

    with open(path, encoding="utf-8") as f:
        try:
            data = json.load(f)
        except json.JSONDecodeError as exc:
            _err(f"research_api_smoke_report.json is not valid JSON: {exc}")
            return

    print(f"  OK: research_api_smoke_report.json")


def main() -> int:
    """Run all output validations."""
    ERRORS.clear()
    WARNINGS.clear()

    print("=== Research Source Output Validation ===\n")

    if not os.path.isdir(OUTPUTS_DIR):
        _warn(f"outputs/ directory not found at {OUTPUTS_DIR}")
    else:
        validate_capabilities_json()
        validate_smoke_report()

    print(f"\nErrors:   {len(ERRORS)}")
    print(f"Warnings: {len(WARNINGS)}")

    if ERRORS:
        print("\nValidation FAILED.")
        return 1

    print("\nValidation passed (warnings are informational).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
